import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import './styles.css';

type GitHubCache={open_pr_count?:number;open_prs?:{number:number;title:string;url:string;updated_at?:string;draft?:boolean;head?:string}[];last_merged_pr?:{number:number;title:string;url:string;merged_at?:string};latest_commit?:{sha?:string;url?:string;date?:string;message?:string};ci?:{state?:string};version_source?:string};
type Project={id:number;name:string;code:string;github_owner:string;github_repo:string;repository_url?:string|null;repository_description?:string|null;repository_visibility?:string|null;default_branch:string;roadmap_path:string;changelog_path:string;logo_path?:string|null;active:boolean;latest_version?:string|null;latest_release_url?:string|null;latest_release_at?:string|null;github_refreshed_at?:string|null;github_last_attempt_at?:string|null;github_sync_status:string;github_sync_error?:string|null;github_cache_json?:string|null;roadmap_current_phase_id?:number|null;roadmap_next_phase_id?:number|null};
type Item={id:number;project_id:number;roadmap_phase_id?:number|null;item_key:string;item_type:string;title:string;description:string;priority:string;status:string;target_release?:string|null;actual_behaviour:string;expected_behaviour:string;testing_instructions:string;criteria:{id:number;description:string;sort_order:number}[];attachments:{id:number;original_name:string;content_type:string;size_bytes:number}[]};
type Release={id:number;project_id:number;planned_version?:string|null;actual_version?:string|null;status:string;release_url?:string|null;created_at:string};
type SyncSummary={active_projects:number;failed_projects:number;status:string;last_successful_sync?:string|null;interval_seconds:number};
type RoadmapPhase={id:number;version?:string|null;title:string;phase_type:string;status:string;sort_order:number;ignored:boolean;items:{id:number;text:string;completed:boolean;sort_order:number}[];linked_register_items:{id:number;item_key:string;title:string;item_type:string;status:string}[]};
type RoadmapIntel={status:string;snapshot_id?:number;source_path?:string;source_sha?:string;fetched_at?:string;parsed_at?:string;error?:string|null;current_phase_id?:number|null;next_phase_id?:number|null;phases:RoadmapPhase[]};

const api=async(path:string,opts?:RequestInit)=>{const r=await fetch(path,opts);if(!r.ok)throw new Error((await r.text())||r.statusText);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null};
const cache=(p:Project):GitHubCache=>{try{return p.github_cache_json?JSON.parse(p.github_cache_json):{}}catch{return {}}};
const relative=(value?:string|null)=>{if(!value)return 'Not yet';const ms=Date.now()-new Date(value).getTime();const mins=Math.max(0,Math.floor(ms/60000));if(mins<1)return 'just now';if(mins<60)return `${mins} min ago`;const hrs=Math.floor(mins/60);if(hrs<24)return `${hrs} ${hrs===1?'hour':'hours'} ago`;const days=Math.floor(hrs/24);if(days===1)return 'yesterday';return `${days} days ago`};
const ciLabel=(state?:string)=>({success:'Passing',failure:'Failing',pending:'Pending',error:'Failing'} as Record<string,string>)[state||'']||'Unknown';
const ciClass=(state?:string)=>state==='success'?'pass':state==='failure'||state==='error'?'fail':state==='pending'?'pending':'unknown';

function App(){
 const [tab,setTab]=useState('Portfolio');const [projects,setProjects]=useState<Project[]>([]);const [items,setItems]=useState<Item[]>([]);const [releases,setReleases]=useState<Release[]>([]);const [summary,setSummary]=useState<SyncSummary|null>(null);const [error,setError]=useState('');const [feedback,setFeedback]=useState(false);const [selectedProject,setSelectedProject]=useState<Project|null>(null);const [roadmap,setRoadmap]=useState('');const [roadmapIntel,setRoadmapIntel]=useState<RoadmapIntel|null>(null);const [prompt,setPrompt]=useState('');const [syncing,setSyncing]=useState(false);
 const load=async(sync=false)=>{try{if(sync){setSyncing(true);await api('/api/projects/refresh-all',{method:'POST'})}const [p,i,r,s]=await Promise.all([api('/api/projects'),api('/api/register'),api('/api/releases'),api('/api/projects/sync-summary')]);setProjects(p);setItems(i);setReleases(r);setSummary(s);setError('')}catch(e:any){setError(e.message)}finally{setSyncing(false)}};
 useEffect(()=>{load(false)},[]);
 const counts=useMemo(()=>Object.fromEntries(projects.map(p=>[p.id,{defects:items.filter(i=>i.project_id===p.id&&i.item_type==='Defect'&&!['Released','Rejected'].includes(i.status)).length,enh:items.filter(i=>i.project_id===p.id&&i.item_type==='Enhancement'&&!['Released','Rejected'].includes(i.status)).length}])),[projects,items]);
 const openProject=async(p:Project,roadmapOnly=false)=>{setSelectedProject(p);setTab('Project');try{await api(`/api/projects/${p.id}/refresh`,{method:'POST'});const updated=(await api('/api/projects')).find((x:Project)=>x.id===p.id)||p;setSelectedProject(updated);setProjects(await api('/api/projects'));const [r,intel]=await Promise.all([api(`/api/projects/${p.id}/roadmap`),api(`/api/projects/${p.id}/roadmap/intelligence`)]);setRoadmap(r.markdown);setRoadmapIntel(intel);setSummary(await api('/api/projects/sync-summary'))}catch(e:any){setRoadmap(`Roadmap unavailable: ${e.message}`);setRoadmapIntel(null)}if(roadmapOnly)setTimeout(()=>document.querySelector('.roadmap-intel')?.scrollIntoView({behavior:'smooth'}),60)};
 return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">⬡</span><div><span>DevHub</span><small>Portfolio Dashboard</small></div></div><nav>{['Portfolio','Projects','Register','Releases','Settings'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className="sync-panel"><div className="sync-panel-title"><span className={`status-dot ${summary?.failed_projects?'bad':'good'}`}/><b>GitHub Sync</b></div><p className={summary?.failed_projects?'warn-text':'good-text'}>{summary?.failed_projects?`${summary.failed_projects} project${summary.failed_projects===1?'':'s'} degraded`:'All systems operational'}</p><small>Last background sync</small><strong>{relative(summary?.last_successful_sync)}</strong><button onClick={()=>load(true)} disabled={syncing}>{syncing?'Refreshing…':'↻ Refresh All'}</button></div></aside><div className="app"><header><div><h1>{tab==='Portfolio'?'Portfolio':'DevHub'}</h1><span>{tab==='Portfolio'?'Overview of all configured projects and their development status.':'Development portfolio & release management'}</span></div><div className="header-actions">{tab==='Portfolio'&&<button onClick={()=>load(true)} disabled={syncing}>{syncing?'Refreshing…':'↻ Refresh All'}</button>}<button className="primary" onClick={()=>setTab('Projects')}>+ Add Project</button><button onClick={()=>setFeedback(true)}>+ Feedback</button></div></header>{error&&<div className="error">{error}</div>}<main>
 {tab==='Portfolio'&&<section><div className="project-grid">{projects.map(p=><ProjectCard key={p.id} project={p} onDetails={()=>openProject(p)} onRoadmap={()=>openProject(p,true)}/>)}{projects.length===0&&<Empty text="Add your first GitHub project to start building the portfolio."/>}</div>{projects.length>0&&<div className="portfolio-footer">Showing {projects.length} of {projects.length} projects</div>}</section>}
 {tab==='Projects'&&<ProjectsView projects={projects} reload={()=>load(false)} openProject={openProject}/>} 
 {tab==='Register'&&<RegisterView items={items} projects={projects}/>} 
 {tab==='Releases'&&<ReleasesView releases={releases} projects={projects} items={items} reload={()=>load(false)} setPrompt={setPrompt}/>} 
 {tab==='Settings'&&<Settings/>}
 {tab==='Project'&&selectedProject&&<ProjectView project={selectedProject} roadmap={roadmap} intelligence={roadmapIntel} counts={counts[selectedProject.id]} onBack={()=>setTab('Portfolio')} onFeedback={()=>setFeedback(true)} onRefresh={()=>openProject(selectedProject)} onIntel={setRoadmapIntel}/>} 
 </main>{feedback&&<FeedbackModal projects={projects} close={()=>setFeedback(false)} saved={()=>{setFeedback(false);load(false)}}/>}{prompt&&<PromptModal prompt={prompt} close={()=>setPrompt('')}/>}</div></div>
}

function ProjectCard({project,onDetails,onRoadmap}:{project:Project;onDetails:()=>void;onRoadmap:()=>void}){const c=cache(project);const pr=c.open_prs?.[0];const merged=c.last_merged_pr;const state=c.ci?.state;return <article className="project-card"><div className="project-card-head"><ProjectIcon project={project}/><div className="project-ident"><div className="project-name-row"><strong>{project.name}</strong>{project.active&&<span className="active-chip">Active</span>}</div><a className="repo-link" href={project.repository_url||`https://github.com/${project.github_owner}/${project.github_repo}`} target="_blank">{project.github_owner}/{project.github_repo}</a></div></div><p className="description">{project.repository_description||'No repository description available.'}</p><div className="metric-grid"><Metric title="Latest Release"><div className="release-value">{project.latest_release_url?<a href={project.latest_release_url} target="_blank">{project.latest_version||'No release'}</a>:<b>{project.latest_version||'No release published'}</b>}</div><small>{c.version_source?`Source: ${c.version_source}`:''}</small></Metric><Metric title="Open PRs"><div className="metric-number">{c.open_pr_count||0}</div>{pr?<a className="metric-link" href={pr.url} target="_blank">#{pr.number} {pr.title}</a>:<small>No open pull requests</small>}</Metric><Metric title="Last Merged PR">{merged?<><a className="metric-link" href={merged.url} target="_blank">#{merged.number} {merged.title}</a><small>Merged {relative(merged.merged_at)}</small></>:<small>No merged pull request detected</small>}</Metric><Metric title="CI Status"><span className={`ci-chip ${ciClass(state)}`}>{ciLabel(state)}</span></Metric></div><div className="roadmap-signal">Roadmap intelligence available in Project Details</div><div className="card-meta"><span><span className={`status-dot ${project.github_sync_status==='Synced'?'good':'bad'}`}/> {project.github_sync_status==='Synced'?`Synced ${relative(project.github_refreshed_at)}`:'GitHub sync failed'}</span><span>Auto-refresh every 15 min</span></div>{project.github_sync_error&&<div className="sync-error">Showing last known good data. {project.github_sync_error}</div>}<div className="card-actions"><button onClick={onRoadmap}>▱ Roadmap</button><button className="primary" onClick={onDetails}>Project Details ›</button></div></article>}
function Metric({title,children}:{title:string;children:React.ReactNode}){return <div className="metric"><span className="metric-title">{title}</span>{children}</div>}
function ProjectIcon({project}:{project:Project}){return project.logo_path?<img className="project-icon" src={`/api/projects/${project.id}/logo`} alt={`${project.name} logo`}/>:<div className="project-icon fallback" aria-label={`${project.name} fallback icon`}>{project.name.slice(0,2).toUpperCase()}</div>}

function RoadmapIntelligence({project,intelligence,raw,onIntel}:{project:Project;intelligence:RoadmapIntel|null;raw:string;onIntel:(v:RoadmapIntel)=>void}){const [mode,setMode]=useState<'structured'|'raw'>('structured');const [busy,setBusy]=useState(false);const current=intelligence?.phases.find(p=>p.id===intelligence.current_phase_id);const next=intelligence?.phases.find(p=>p.id===intelligence.next_phase_id);const reparse=async()=>{setBusy(true);try{await api(`/api/projects/${project.id}/roadmap/reparse`,{method:'POST'});onIntel(await api(`/api/projects/${project.id}/roadmap/intelligence`))}finally{setBusy(false)}};return <div className="panel roadmap-intel full"><div className="roadmap-toolbar"><div><h3>Roadmap Intelligence</h3><small>{intelligence?.status||'Unknown'}{intelligence?.error?` · ${intelligence.error}`:''}</small></div><div className="actions"><button onClick={()=>setMode('structured')} className={mode==='structured'?'primary':''}>Structured</button><button onClick={()=>setMode('raw')} className={mode==='raw'?'primary':''}>Raw Markdown</button><button onClick={reparse} disabled={busy}>{busy?'Reparsing…':'Reparse Roadmap'}</button></div></div>{mode==='structured'?<><div className="roadmap-summary"><div><span>Current phase</span><b>{current?`${current.version||''} ${current.title}`.trim():'Unknown'}</b></div><div><span>Next phase</span><b>{next?`${next.version||''} ${next.title}`.trim():'Unknown'}</b></div><div><span>Parse status</span><b>{intelligence?.status||'Unknown'}</b></div></div><div className="phase-list">{intelligence?.phases.filter(p=>!p.ignored).map(p=><article className={`phase-card ${p.id===intelligence.current_phase_id?'current':''}`} key={p.id}><div className="phase-head"><div><span className="phase-version">{p.version||p.phase_type}</span><h4>{p.title}</h4></div><span className={`phase-status ${p.status.toLowerCase().replaceAll(' ','-')}`}>{p.status}</span></div>{p.items.length>0&&<ul>{p.items.map(i=><li key={i.id}>{i.completed?'✓':'○'} {i.text}</li>)}</ul>}<small>{p.linked_register_items.length} linked register item{p.linked_register_items.length===1?'':'s'}</small></article>)}{!intelligence?.phases.length&&<Empty text="No structured roadmap phases could be identified."/>}</div></>:<div className="roadmap raw-roadmap"><ReactMarkdown>{raw}</ReactMarkdown></div>}</div>}

function ProjectView({project,roadmap,intelligence,counts,onBack,onFeedback,onRefresh,onIntel}:{project:Project;roadmap:string;intelligence:RoadmapIntel|null;counts?:{defects:number;enh:number};onBack:()=>void;onFeedback:()=>void;onRefresh:()=>void;onIntel:(v:RoadmapIntel)=>void}){const c=cache(project);const current=intelligence?.phases.find(p=>p.id===intelligence.current_phase_id);const next=intelligence?.phases.find(p=>p.id===intelligence.next_phase_id);return <section><button className="back" onClick={onBack}>← Portfolio</button><div className="project-title"><div className="project-title-ident"><ProjectIcon project={project}/><div><h2>{project.name}</h2><p>{project.github_owner}/{project.github_repo}</p></div></div><div className="actions"><a href={project.repository_url||`https://github.com/${project.github_owner}/${project.github_repo}`} target="_blank">Repository</a>{project.latest_release_url&&<a href={project.latest_release_url} target="_blank">Latest release</a>}<button onClick={onRefresh}>Refresh</button><button onClick={onFeedback}>Add Feedback</button></div></div><div className="details-grid"><div className="panel"><h3>Repository</h3><dl><dt>Visibility</dt><dd>{project.repository_visibility||'Unknown'}</dd><dt>Default branch</dt><dd>{project.default_branch}</dd><dt>Current release</dt><dd>{project.latest_version||'Not detected'}</dd><dt>Version source</dt><dd>{c.version_source||'Unknown'}</dd><dt>CI</dt><dd>{ciLabel(c.ci?.state)}</dd><dt>Last synced</dt><dd>{project.github_refreshed_at?new Date(project.github_refreshed_at).toLocaleString():project.github_sync_status}</dd><dt>Defects</dt><dd>{counts?.defects||0}</dd><dt>Enhancements</dt><dd>{counts?.enh||0}</dd></dl></div><div className="panel"><h3>Roadmap summary</h3><dl><dt>Current</dt><dd>{current?`${current.version||''} ${current.title}`.trim():'Unknown'}</dd><dt>Next</dt><dd>{next?`${next.version||''} ${next.title}`.trim():'Unknown'}</dd><dt>Next items</dt><dd>{next?.items.length||0}</dd><dt>Parse status</dt><dd>{intelligence?.status||'Unknown'}</dd></dl><h3 className="spaced">Open pull requests</h3>{c.open_prs?.length?c.open_prs.map(pr=><div className="row" key={pr.number}><div><a href={pr.url} target="_blank"><b>#{pr.number} {pr.title}</b></a><small>{pr.head}{pr.draft?' · Draft':''}</small></div><span>{relative(pr.updated_at)}</span></div>):<Empty text="No open pull requests."/>}</div><RoadmapIntelligence project={project} intelligence={intelligence} raw={roadmap} onIntel={onIntel}/></div></section>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}

function ProjectsView({projects,reload,openProject}:{projects:Project[];reload:()=>void;openProject:(p:Project)=>void}){const [url,setUrl]=useState('');const [preview,setPreview]=useState<any>(null);const [logo,setLogo]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [err,setErr]=useState('');const discover=async()=>{try{setBusy(true);setPreview(await api('/api/projects/discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repository_url:url})}));setErr('')}catch(e:any){setErr(e.message)}finally{setBusy(false)}};const save=async()=>{try{setBusy(true);const p=await api('/api/projects/from-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repository_url:url,roadmap_path:preview?.roadmap_path||undefined,changelog_path:preview?.changelog_path||undefined})});if(logo){const fd=new FormData();fd.append('file',logo);await api(`/api/projects/${p.id}/logo`,{method:'POST',body:fd})}setUrl('');setPreview(null);setLogo(null);reload();setErr('')}catch(e:any){setErr(e.message)}finally{setBusy(false)}};const refresh=async(id:number)=>{await api(`/api/projects/${id}/refresh`,{method:'POST'});reload()};return <section><h2>Projects</h2><div className="split"><div className="panel form"><h3>Add project</h3><label>GitHub repository URL<input value={url} onChange={e=>{setUrl(e.target.value);setPreview(null)}} placeholder="https://github.com/owner/repository"/></label><button className="primary" disabled={!url||busy} onClick={discover}>{busy?'Checking…':'Continue'}</button>{err&&<div className="sync-error">{err}</div>}{preview&&<div className="preview"><h3>{preview.name}</h3><p>{preview.description||'No repository description'}</p><dl><dt>Repository</dt><dd>{preview.owner}/{preview.repo}</dd><dt>Branch</dt><dd>{preview.default_branch}</dd><dt>Visibility</dt><dd>{preview.visibility}</dd><dt>Roadmap</dt><dd>{preview.roadmap_path||'Not detected'}</dd><dt>Changelog</dt><dd>{preview.changelog_path||'Not detected'}</dd></dl><label>Project logo/icon<input type="file" accept="image/svg+xml,image/png,image/webp,image/jpeg" onChange={e=>setLogo(e.target.files?.[0]||null)}/></label><button className="primary" onClick={save} disabled={busy}>Add project</button></div>}</div><div className="panel"><h3>Configured projects</h3>{projects.map(p=><div className="row" key={p.id}><div onClick={()=>openProject(p)}><b>{p.name}</b><small>{p.github_owner}/{p.github_repo} · {p.github_sync_status}</small></div><button onClick={()=>refresh(p.id)}>Refresh</button></div>)}{!projects.length&&<Empty text="No projects configured."/>}</div></div></section>}

function RegisterView({items,projects}:{items:Item[];projects:Project[]}){const [project,setProject]=useState('');const [phase,setPhase]=useState('');const [phases,setPhases]=useState<RoadmapPhase[]>([]);useEffect(()=>{if(!project){setPhases([]);setPhase('');return}api(`/api/projects/${project}/roadmap/intelligence`).then((x:RoadmapIntel)=>setPhases(x.phases||[])).catch(()=>setPhases([]))},[project]);const filtered=items.filter(i=>(!project||String(i.project_id)===project)&&(!phase||String(i.roadmap_phase_id||'')===phase));return <section><div className="section-title"><div><h2>Defect & enhancement register</h2><p>Filter work by project and roadmap phase.</p></div></div><div className="filter-bar"><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">All projects</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Roadmap phase<select value={phase} onChange={e=>setPhase(e.target.value)} disabled={!project}><option value="">All phases</option>{phases.map(p=><option value={p.id} key={p.id}>{p.version||p.phase_type} {p.title}</option>)}</select></label></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Project</th><th>Roadmap</th><th>Type</th><th>Title</th><th>Priority</th><th>Status</th><th>Target</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td>{i.item_key}</td><td>{projects.find(p=>p.id===i.project_id)?.name}</td><td>{i.roadmap_phase_id?phases.find(p=>p.id===i.roadmap_phase_id)?.version||`#${i.roadmap_phase_id}`:'Unassigned'}</td><td>{i.item_type}</td><td>{i.title}</td><td>{i.priority}</td><td>{i.status}</td><td>{i.target_release||'Next'}</td></tr>)}</tbody></table></div>{!filtered.length&&<Empty text="No register items match the selected roadmap context."/>}</section>}

function ReleasesView({releases,projects,items,reload,setPrompt}:{releases:Release[];projects:Project[];items:Item[];reload:()=>void;setPrompt:(x:string)=>void}){const [projectId,setProjectId]=useState('');const [intel,setIntel]=useState<RoadmapIntel|null>(null);const eligible=items.filter(i=>String(i.project_id)===projectId&&['Approved','Planned','New','Reviewed'].includes(i.status));const [selected,setSelected]=useState<number[]>([]);useEffect(()=>{if(!projectId){setIntel(null);return}api(`/api/projects/${projectId}/roadmap/intelligence`).then(setIntel).catch(()=>setIntel(null))},[projectId]);const next=intel?.phases.find(p=>p.id===intel.next_phase_id);const suggested=eligible.filter(i=>next&&i.roadmap_phase_id===next.id);const build=async()=>{const r=await api('/api/releases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:Number(projectId),item_ids:selected})});const p=await api(`/api/releases/${r.id}/prompt`,{method:'POST'});setPrompt(p.prompt);reload()};return <section><h2>Releases</h2><div className="split"><div className="panel"><h3>Next Release Builder</h3><label>Project<select value={projectId} onChange={e=>{setProjectId(e.target.value);setSelected([])}}><option value="">Select project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{projectId&&<div className="roadmap-builder-context"><span>Current release</span><b>{projects.find(p=>String(p.id)===projectId)?.latest_version||'Unknown'}</b><span>Next roadmap phase</span><b>{next?`${next.version||''} ${next.title}`.trim():'Unknown'}</b><span>Suggested linked scope</span><b>{suggested.length}</b></div>}{eligible.map(i=><label className="check" key={i.id}><input type="checkbox" checked={selected.includes(i.id)} onChange={e=>setSelected(e.target.checked?[...selected,i.id]:selected.filter(x=>x!==i.id))}/><span><b>{i.item_key}</b> {i.title}{suggested.some(s=>s.id===i.id)&&<small>Suggested by next roadmap phase</small>}</span></label>)}<button className="primary" disabled={!projectId||!selected.length} onClick={build}>Build Release Prompt</button></div><div className="panel"><h3>Release history</h3>{releases.map(r=><div className="row" key={r.id}><div><b>{projects.find(p=>p.id===r.project_id)?.name}</b><small>{r.actual_version||r.planned_version||'Version pending'}</small></div><span>{r.status}</span></div>)}{!releases.length&&<Empty text="No release records yet."/>}</div></div></section>}

function Settings(){return <section><h2>Settings</h2><div className="panel"><h3>GitHub connection</h3><p>GitHub credentials are configured using Home Assistant add-on options. DevHub never returns the configured token through its API.</p></div></section>}
function FeedbackModal({projects,close,saved}:{projects:Project[];close:()=>void;saved:()=>void}){const [project,setProject]=useState('');const [title,setTitle]=useState('');const [description,setDescription]=useState('');const save=async()=>{await api('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:Number(project),item_type:'Enhancement',title,description,priority:'Medium',status:'New',actual_behaviour:'',expected_behaviour:'',testing_instructions:'',criteria:[]})});saved()};return <div className="modal-bg"><div className="modal"><div className="modal-head"><h2>Add Feedback</h2><button onClick={close}>×</button></div><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">Select project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="modal-actions"><button onClick={close}>Cancel</button><button className="primary" disabled={!project||!title} onClick={save}>Save</button></div></div></div>}
function PromptModal({prompt,close}:{prompt:string;close:()=>void}){return <div className="modal-bg"><div className="modal wide"><div className="modal-head"><h2>Release Prompt</h2><button onClick={close}>×</button></div><pre className="prompt">{prompt}</pre><div className="modal-actions"><button onClick={()=>navigator.clipboard.writeText(prompt)}>Copy prompt</button><button className="primary" onClick={close}>Done</button></div></div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
