import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import './styles.css';

type GitHubCache={open_pr_count?:number;open_prs?:{number:number;title:string;url:string;updated_at?:string;draft?:boolean;head?:string}[];last_merged_pr?:{number:number;title:string;url:string;merged_at?:string};latest_commit?:{sha?:string;url?:string;date?:string;message?:string};ci?:{state?:string}};
type Project={id:number;name:string;code:string;github_owner:string;github_repo:string;repository_url?:string|null;repository_description?:string|null;repository_visibility?:string|null;default_branch:string;roadmap_path:string;changelog_path:string;logo_path?:string|null;active:boolean;latest_version?:string|null;latest_release_url?:string|null;latest_release_at?:string|null;github_refreshed_at?:string|null;github_last_attempt_at?:string|null;github_sync_status:string;github_sync_error?:string|null;github_cache_json?:string|null};
type Item={id:number;project_id:number;item_key:string;item_type:string;title:string;description:string;priority:string;status:string;target_release?:string|null;actual_behaviour:string;expected_behaviour:string;testing_instructions:string;criteria:{id:number;description:string;sort_order:number}[];attachments:{id:number;original_name:string;content_type:string;size_bytes:number}[]};
type Release={id:number;project_id:number;planned_version?:string|null;actual_version?:string|null;status:string;release_url?:string|null;created_at:string};

const api=async(path:string,opts?:RequestInit)=>{const r=await fetch(path,opts);if(!r.ok)throw new Error((await r.text())||r.statusText);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null};
const cache=(p:Project):GitHubCache=>{try{return p.github_cache_json?JSON.parse(p.github_cache_json):{}}catch{return {}}};
const relative=(value?:string|null)=>{if(!value)return 'Not yet';const ms=Date.now()-new Date(value).getTime();const mins=Math.max(1,Math.round(ms/60000));if(mins<60)return `${mins} min ago`;const hrs=Math.round(mins/60);if(hrs<24)return `${hrs} ${hrs===1?'hour':'hours'} ago`;const days=Math.round(hrs/24);return `${days} ${days===1?'day':'days'} ago`};
const ciLabel=(state?:string)=>({success:'Passing',failure:'Failing',pending:'Pending',error:'Failing'} as Record<string,string>)[state||'']||'Unknown';

function App(){
 const [tab,setTab]=useState('Portfolio');const [projects,setProjects]=useState<Project[]>([]);const [items,setItems]=useState<Item[]>([]);const [releases,setReleases]=useState<Release[]>([]);const [error,setError]=useState('');const [feedback,setFeedback]=useState(false);const [selectedProject,setSelectedProject]=useState<Project|null>(null);const [roadmap,setRoadmap]=useState('');const [prompt,setPrompt]=useState('');const [syncing,setSyncing]=useState(false);
 const load=async(sync=false)=>{try{if(sync){setSyncing(true);await api('/api/projects/refresh-all',{method:'POST'})}setProjects(await api('/api/projects'));setItems(await api('/api/register'));setReleases(await api('/api/releases'));setError('')}catch(e:any){setError(e.message)}finally{setSyncing(false)}};
 useEffect(()=>{load(true)},[]);
 useEffect(()=>{const id=window.setInterval(()=>load(true),15*60*1000);return()=>clearInterval(id)},[]);
 const counts=useMemo(()=>Object.fromEntries(projects.map(p=>[p.id,{defects:items.filter(i=>i.project_id===p.id&&i.item_type==='Defect'&&!['Released','Rejected'].includes(i.status)).length,enh:items.filter(i=>i.project_id===p.id&&i.item_type==='Enhancement'&&!['Released','Rejected'].includes(i.status)).length}])),[projects,items]);
 const openProject=async(p:Project)=>{setSelectedProject(p);setTab('Project');try{await api(`/api/projects/${p.id}/refresh`,{method:'POST'});const updated=(await api('/api/projects')).find((x:Project)=>x.id===p.id)||p;setSelectedProject(updated);setProjects(await api('/api/projects'));const r=await api(`/api/projects/${p.id}/roadmap`);setRoadmap(r.markdown)}catch(e:any){setRoadmap(`Roadmap unavailable: ${e.message}`)}};
 return <div className="app-shell"><aside><div className="brand">◈ <span>DevHub</span></div><nav>{['Portfolio','Projects','Register','Releases','Settings'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav></aside><div className="app"><header><div><h1>{tab==='Portfolio'?'Dashboard':'DevHub'}</h1><span>Development portfolio & release management</span></div><div className="header-actions"><button onClick={()=>load(true)} disabled={syncing}>{syncing?'Syncing…':'Refresh GitHub'}</button><button className="primary" onClick={()=>setFeedback(true)}>+ Feedback</button></div></header>{error&&<div className="error">{error}</div>}<main>
 {tab==='Portfolio'&&<section><div className="section-title"><div><h2>Projects</h2><p>Live release, pull request and CI status from GitHub.</p></div><button className="primary" onClick={()=>setTab('Projects')}>+ New Project</button></div><div className="project-grid">{projects.map(p=><ProjectCard key={p.id} project={p} onOpen={()=>openProject(p)}/>) }{projects.length===0&&<Empty text="Add your first GitHub project to start building the portfolio."/>}</div></section>}
 {tab==='Projects'&&<ProjectsView projects={projects} reload={()=>load(false)} openProject={openProject}/>} 
 {tab==='Register'&&<RegisterView items={items} projects={projects}/>} 
 {tab==='Releases'&&<ReleasesView releases={releases} projects={projects} items={items} reload={()=>load(false)} setPrompt={setPrompt}/>} 
 {tab==='Settings'&&<Settings/>}
 {tab==='Project'&&selectedProject&&<ProjectView project={selectedProject} roadmap={roadmap} counts={counts[selectedProject.id]} onBack={()=>setTab('Portfolio')} onFeedback={()=>setFeedback(true)} onRefresh={()=>openProject(selectedProject)}/>} 
 </main>{feedback&&<FeedbackModal projects={projects} close={()=>setFeedback(false)} saved={()=>{setFeedback(false);load(false)}}/>}{prompt&&<PromptModal prompt={prompt} close={()=>setPrompt('')}/>}</div></div>
}

function ProjectCard({project,onOpen}:{project:Project;onOpen:()=>void}){const c=cache(project);const pr=c.open_prs?.[0];const merged=c.last_merged_pr;return <article className="project-card"><div className="project-card-head"><ProjectIcon project={project}/><div className="project-ident"><strong>{project.name}</strong><small>{project.github_repo}</small></div><span className={`sync-dot ${project.github_sync_status==='Synced'?'ok':'warn'}`} title={project.github_sync_error||project.github_sync_status}/></div>{project.repository_description&&<p className="description">{project.repository_description}</p>}<div className="status-grid"><div><span>Current Release</span>{project.latest_release_url?<a href={project.latest_release_url} target="_blank" className="release-pill">{project.latest_version||'No release'}</a>:<b>{project.latest_version||'No release'}</b>}</div><div><span>Open PR{(c.open_pr_count||0)!==1?'s':''}</span><b>{c.open_pr_count||0}</b>{pr&&<a href={pr.url} target="_blank">#{pr.number} {pr.title}</a>}</div><div><span>Last Merged PR</span>{merged?<><a href={merged.url} target="_blank">#{merged.number} {merged.title}</a><small className="positive">{relative(merged.merged_at)}</small></>:<b>None</b>}</div></div><div className="card-meta"><span>CI: <b>{ciLabel(c.ci?.state)}</b></span><span>{project.github_refreshed_at?`Synced ${relative(project.github_refreshed_at)}`:project.github_sync_status}</span></div>{project.github_sync_error&&<div className="sync-error">GitHub sync failed, showing last known data.</div>}<div className="card-actions"><button onClick={onOpen}>Roadmap</button><button onClick={onOpen}>Project Details</button></div></article>}
function ProjectIcon({project}:{project:Project}){return project.logo_path?<img className="project-icon" src={`/api/projects/${project.id}/logo`} alt=""/>:<div className="project-icon fallback">{project.name.slice(0,2).toUpperCase()}</div>}
function ProjectView({project,roadmap,counts,onBack,onFeedback,onRefresh}:{project:Project;roadmap:string;counts?:{defects:number;enh:number};onBack:()=>void;onFeedback:()=>void;onRefresh:()=>void}){const c=cache(project);return <section><button className="back" onClick={onBack}>← Portfolio</button><div className="project-title"><div className="project-title-ident"><ProjectIcon project={project}/><div><h2>{project.name}</h2><p>{project.github_owner}/{project.github_repo}</p></div></div><div className="actions"><a href={project.repository_url||`https://github.com/${project.github_owner}/${project.github_repo}`} target="_blank">Repository</a>{project.latest_release_url&&<a href={project.latest_release_url} target="_blank">Latest release</a>}<button onClick={onRefresh}>Refresh</button><button onClick={onFeedback}>Add Feedback</button></div></div><div className="details-grid"><div className="panel"><h3>Repository</h3><dl><dt>Visibility</dt><dd>{project.repository_visibility||'Unknown'}</dd><dt>Default branch</dt><dd>{project.default_branch}</dd><dt>Current release</dt><dd>{project.latest_version||'Not detected'}</dd><dt>Last release</dt><dd>{project.latest_release_at?new Date(project.latest_release_at).toLocaleString():'Not detected'}</dd><dt>CI</dt><dd>{ciLabel(c.ci?.state)}</dd><dt>Last synced</dt><dd>{project.github_refreshed_at?new Date(project.github_refreshed_at).toLocaleString():project.github_sync_status}</dd><dt>Defects</dt><dd>{counts?.defects||0}</dd><dt>Enhancements</dt><dd>{counts?.enh||0}</dd></dl></div><div className="panel"><h3>Open pull requests</h3>{c.open_prs?.length?c.open_prs.map(pr=><div className="row" key={pr.number}><div><a href={pr.url} target="_blank"><b>#{pr.number} {pr.title}</b></a><small>{pr.head}{pr.draft?' · Draft':''}</small></div><span>{relative(pr.updated_at)}</span></div>):<Empty text="No open pull requests."/>}<h3 className="spaced">Last merged</h3>{c.last_merged_pr?<div className="row"><div><a href={c.last_merged_pr.url} target="_blank"><b>#{c.last_merged_pr.number} {c.last_merged_pr.title}</b></a></div><span>{relative(c.last_merged_pr.merged_at)}</span></div>:<Empty text="No merged pull request detected."/>}</div><div className="panel roadmap full"><h3>Roadmap</h3><ReactMarkdown>{roadmap}</ReactMarkdown></div></div></section>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function ProjectsView({projects,reload,openProject}:{projects:Project[];reload:()=>void;openProject:(p:Project)=>void}){const [url,setUrl]=useState('');const [preview,setPreview]=useState<any>(null);const [logo,setLogo]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [err,setErr]=useState('');const discover=async()=>{try{setBusy(true);setPreview(await api('/api/projects/discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repository_url:url})}));setErr('')}catch(e:any){setErr(e.message)}finally{setBusy(false)}};const save=async()=>{try{setBusy(true);const p=await api('/api/projects/from-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({repository_url:url,roadmap_path:preview?.roadmap_path||undefined,changelog_path:preview?.changelog_path||undefined})});if(logo){const fd=new FormData();fd.append('file',logo);await api(`/api/projects/${p.id}/logo`,{method:'POST',body:fd})}setUrl('');setPreview(null);setLogo(null);reload();setErr('')}catch(e:any){setErr(e.message)}finally{setBusy(false)}};const refresh=async(id:number)=>{await api(`/api/projects/${id}/refresh`,{method:'POST'});reload()};return <section><h2>Projects</h2><div className="split"><div className="panel form"><h3>Add project</h3><label>GitHub repository URL<input value={url} onChange={e=>{setUrl(e.target.value);setPreview(null)}} placeholder="https://github.com/owner/repository"/></label><button className="primary" disabled={!url||busy} onClick={discover}>{busy?'Checking…':'Continue'}</button>{err&&<div className="sync-error">{err}</div>}{preview&&<div className="preview"><h3>{preview.name}</h3><p>{preview.description||'No repository description'}</p><dl><dt>Repository</dt><dd>{preview.owner}/{preview.repo}</dd><dt>Branch</dt><dd>{preview.default_branch}</dd><dt>Visibility</dt><dd>{preview.visibility}</dd><dt>Roadmap</dt><dd>{preview.roadmap_path||'Not detected'}</dd><dt>Changelog</dt><dd>{preview.changelog_path||'Not detected'}</dd></dl><label>Project logo/icon<input type="file" accept="image/svg+xml,image/png,image/webp,image/jpeg" onChange={e=>setLogo(e.target.files?.[0]||null)}/></label><button className="primary" onClick={save} disabled={busy}>Add project</button></div>}</div><div className="panel"><h3>Configured projects</h3>{projects.map(p=><div className="row" key={p.id}><div onClick={()=>openProject(p)}><b>{p.name}</b><small>{p.github_owner}/{p.github_repo} · {p.github_sync_status}</small></div><button onClick={()=>refresh(p.id)}>Refresh</button></div>)}{!projects.length&&<Empty text="No projects configured."/>}</div></div></section>}
function RegisterView({items,projects}:{items:Item[];projects:Project[]}){return <section><h2>Defect & enhancement register</h2><div className="table-wrap"><table><thead><tr><th>ID</th><th>Project</th><th>Type</th><th>Title</th><th>Priority</th><th>Status</th><th>Target</th><th>Criteria</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.item_key}</td><td>{projects.find(p=>p.id===i.project_id)?.name}</td><td>{i.item_type}</td><td>{i.title}</td><td><span className="chip">{i.priority}</span></td><td>{i.status}</td><td>{i.target_release||'Next'}</td><td>{i.criteria.length}</td></tr>)}</tbody></table></div>{!items.length&&<Empty text="No feedback items yet."/>}</section>}
function ReleasesView({releases,projects,items,reload,setPrompt}:{releases:Release[];projects:Project[];items:Item[];reload:()=>void;setPrompt:(x:string)=>void}){const [projectId,setProjectId]=useState('');const eligible=items.filter(i=>String(i.project_id)===projectId&&['Approved','Planned','New','Reviewed'].includes(i.status));const [selected,setSelected]=useState<number[]>([]);const build=async()=>{const r=await api('/api/releases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:Number(projectId),item_ids:selected})});const p=await api(`/api/releases/${r.id}/prompt`,{method:'POST'});setPrompt(p.prompt);reload()};return <section><h2>Releases</h2><div className="split"><div className="panel"><h3>Next Release Builder</h3><label>Project<select value={projectId} onChange={e=>{setProjectId(e.target.value);setSelected([])}}><option value="">Select project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{eligible.map(i=><label className="check" key={i.id}><input type="checkbox" checked={selected.includes(i.id)} onChange={e=>setSelected(e.target.checked?[...selected,i.id]:selected.filter(x=>x!==i.id))}/><span><b>{i.item_key}</b> {i.title}<small>{i.item_type} · {i.priority} · {i.criteria.length} criteria</small></span></label>)}<button className="primary" disabled={!projectId||!selected.length} onClick={build}>Generate release prompt</button></div><div className="panel"><h3>Release history</h3>{releases.map(r=><div className="row" key={r.id}><div><b>{projects.find(p=>p.id===r.project_id)?.name} {r.actual_version||r.planned_version||'Next release'}</b><small>{r.status} · {new Date(r.created_at).toLocaleString()}</small></div><span className="chip">{r.status}</span></div>)}{!releases.length&&<Empty text="No release records yet."/>}</div></div></section>}
function Settings(){return <section><h2>Settings</h2><div className="panel"><h3>GitHub authentication</h3><p>Public repositories work without a token, subject to GitHub rate limits. Configure a GitHub token through Home Assistant add-on options for higher limits or access to private projects.</p><p>GitHub metadata refreshes when the dashboard or project details are opened, on manual refresh, and approximately every 15 minutes while DevHub is open.</p></div></section>}
function FeedbackModal({projects,close,saved}:{projects:Project[];close:()=>void;saved:()=>void}){const [f,setF]=useState({project_id:'',item_type:'Defect',title:'',description:'',priority:'Medium',actual_behaviour:'',expected_behaviour:'',testing_instructions:'',criteria:''});const [files,setFiles]=useState<FileList|null>(null);const save=async(e:any)=>{e.preventDefault();const criteria=f.criteria.split('\n').filter(Boolean).map((description,i)=>({description,sort_order:i}));const item=await api('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,project_id:Number(f.project_id),criteria})});if(files?.length){const fd=new FormData();Array.from(files).forEach(x=>fd.append('files',x));await api(`/api/register/${item.id}/attachments`,{method:'POST',body:fd})}saved()};return <div className="modal-bg"><form className="modal" onSubmit={save}><div className="modal-head"><h2>Add feedback</h2><button type="button" onClick={close}>×</button></div><label>Project<select required value={f.project_id} onChange={e=>setF({...f,project_id:e.target.value})}><option value="">Select project</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="two"><label>Type<select value={f.item_type} onChange={e=>setF({...f,item_type:e.target.value})}>{['Defect','Enhancement','UX Improvement','Technical Debt','Performance','Security','Documentation'].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Notes<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Actual behaviour<textarea value={f.actual_behaviour} onChange={e=>setF({...f,actual_behaviour:e.target.value})}/></label><label>Expected behaviour<textarea value={f.expected_behaviour} onChange={e=>setF({...f,expected_behaviour:e.target.value})}/></label><label>Acceptance criteria <small>one per line</small><textarea value={f.criteria} onChange={e=>setF({...f,criteria:e.target.value})}/></label><label>Testing instructions<textarea value={f.testing_instructions} onChange={e=>setF({...f,testing_instructions:e.target.value})}/></label><label>Evidence<input type="file" multiple accept="image/*,video/*" onChange={e=>setFiles(e.target.files)}/></label><div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary">Save feedback</button></div></form></div>}
function PromptModal({prompt,close}:{prompt:string;close:()=>void}){return <div className="modal-bg"><div className="modal wide"><div className="modal-head"><h2>Release prompt</h2><button onClick={close}>×</button></div><pre className="prompt">{prompt}</pre><div className="modal-actions"><button onClick={close}>Close</button><button className="primary" onClick={()=>navigator.clipboard.writeText(prompt)}>Copy Prompt</button></div></div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
